
import {
  LayoutDashboard,
  Users,
  CalendarCheck,
  Wallet,
  Settings,
  QrCode,
  ScanLine,
  Home,
  HandCoins,
  FileText,
  ScrollText,
  Database,
  Map,
  KeyRound,
  LogOut,
  BarChart3,
  FileClock,
  Upload,
} from 'lucide-react';

export const navItems = [
  { href: '/home', icon: Home, label: 'الشاشة الرئيسية', adminOnly: false },
  { href: '/visits', icon: Map, label: 'تسجيل زيارة', adminOnly: false },
  { href: '/requests', icon: FileText, label: 'طلباتي', adminOnly: false },
  { href: '/admin/dashboard', icon: LayoutDashboard, label: 'لوحة التحكم', adminOnly: true },
  { href: '/attendance', icon: CalendarCheck, label: 'سجل حضوري', adminOnly: false },
  { href: '/admin/employees', icon: Users, label: 'إدارة الموظفين', adminOnly: true },
  { href: '/admin/reports', icon: BarChart3, label: 'التقارير العامة', adminOnly: true },
  { href: '/admin/reports/monthly-employee', icon: FileClock, label: 'تقرير الموظف الشهري', adminOnly: true },
  { href: '/admin/visits', icon: Map, label: 'مراجعة الزيارات', adminOnly: true },
  { href: '/admin/requests', icon: FileText, label: 'طلبات الموظفين', adminOnly: true },
  { href: '/admin/attendance', icon: CalendarCheck, label: 'مراقبة الحضور', adminOnly: true },
  { href: '/admin/attendance-upload', icon: Upload, label: 'رفع السجلات من ماكينة البصمة', adminOnly: true },
  { href: '/admin/payroll', icon: Wallet, label: 'الرواتب الشهرية', adminOnly: true },
  { href: '/admin/loans', icon: HandCoins, label: 'السجلات المالية', adminOnly: true },
  { href: '/admin/login-logs', icon: KeyRound, label: 'سجل الدخول', adminOnly: true, superAdminOnly: true },
  { href: '/admin/regulations', icon: ScrollText, label: 'اللوائح والقواعد', adminOnly: true },
  { href: '/admin/database', icon: Database, label: 'إدارة البيانات', adminOnly: true, superAdminOnly: true },
  { href: '/admin/settings', icon: Settings, label: 'الإعدادات الفنية', adminOnly: true, superAdminOnly: true },
  { href: '/qr-display', icon: QrCode, label: 'عرض QR Code', adminOnly: true },
  { href: '/scanner', icon: ScanLine, label: 'تسجيل حضور و انصراف', adminOnly: false },
  { href: '/logout', icon: LogOut, label: 'إظهار زر تسجيل الخروج', adminOnly: false },
];
